module:
    hugoVersion:
        extended: true
        min: "0.87.0"
baseURL: https://frankzhao.net/
title: Frank Zhao
keywords: Frank Zhao
paginate: 10
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    github: 'https://github.com/frankzhao'
    linkedin: 'https://linkedin.com/frankzhao-au'
  footer:
    hidePowered: true
    since: 2024
    copyright: Frank Zhao
  prefix:
    h2: ""
    h3: ""
menu:
  navs:
    - name: Blog
      params:
        img: /img/pencil.png
      url: 'https://blog.frankzhao.net'
      weight: 1
    - name: Projects
      params:
        img: /img/file.png
      url: '/projects'
      weight: 1

    - name: Tools
      params:
        img: /img/toolbox.png
      url: '/tools'
      weight: 1
